### ISSUE TITLE
Unable to find tunnel URL message

### ISSUE THREAD

**Issue by shahiddev** [Azure/vsce#1]
Working through the documentation when I went to debug the webapi sample (dotnet core/ VS code) I saw this error message. 
![image](https://user-images.githubusercontent.com/11890711/37460124-33fe1fa0-2842-11e8-84e4-d6aee51f8c3d.png)

Updating the web front end to call the backend as per the sample and running that also gave same message however I was able to continue and because I already had the font end page open. 
Debugging across from front end to webapi still worked ok

**Comment by YuzorMa** [comment]
Hi Shahid.  While VSCE is in Private Preview, we're tracking issues through our Private Slack channel (you should have been invited).  Can you please re-post the issue there.  Thanks.
