### ISSUE TITLE
 vsce list gives error: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by shahiddev** [Azure/vsce#2]
Windows 10 using powershell and CMD give same error

Visual Studio Connected Environment CLI
0.1.20180308.3

**Comment by YuzorMa** [comment]
Hi Shahid.  While VSCE is in Private Preview, we're tracking issues through our Private Slack channel (you should have been invited).  Can you please re-post the issue there and include the RequestId so we can track down what went wrong.
